package com.example.smartfamilygrocerylist.security

import java.security.SecureRandom
import java.security.spec.KeySpec
import javax.crypto.Cipher
import javax.crypto.SecretKeyFactory
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.spec.PBEKeySpec
import javax.crypto.spec.SecretKeySpec

object Cryptography {
    private const val ITERATIONS = 1000
    private const val KEY_LENGTH = 256
    private const val SALT_LENGTH = 16
    private const val IV_LENGTH = 12 // GCM standard IV size
    private const val TAG_LENGTH_BIT = 128

    /**
     * Derives a SecretKeySpec from a human-readable passphrase using PBKDF2.
     */
    private fun deriveKey(passphrase: String, salt: ByteArray): SecretKeySpec {
        val factory = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256")
        val spec: KeySpec = PBEKeySpec(passphrase.toCharArray(), salt, ITERATIONS, KEY_LENGTH)
        val tmp = factory.generateSecret(spec)
        return SecretKeySpec(tmp.encoded, "AES")
    }

    /**
     * Encrypts plain text using AES-256-GCM.
     * Returns a Base64 encoded string containing the salt, iv, and cipher text.
     */
    fun encrypt(plainText: String, passphrase: String): String {
        if (passphrase.isEmpty()) return plainText
        
        try {
            // Generate random salt and IV
            val random = SecureRandom()
            val salt = ByteArray(SALT_LENGTH)
            random.nextBytes(salt)
            val iv = ByteArray(IV_LENGTH)
            random.nextBytes(iv)

            // Derive key
            val keySpec = deriveKey(passphrase, salt)

            // Configure cipher
            val cipher = Cipher.getInstance("AES/GCM/NoPadding")
            val gcmSpec = GCMParameterSpec(TAG_LENGTH_BIT, iv)
            cipher.init(Cipher.ENCRYPT_MODE, keySpec, gcmSpec)

            // Encrypt
            val cipherText = cipher.doFinal(plainText.toByteArray(Charsets.UTF_8))

            // Pack bytes: [salt (16b)] + [iv (12b)] + [cipherText]
            val packed = ByteArray(SALT_LENGTH + IV_LENGTH + cipherText.size)
            System.arraycopy(salt, 0, packed, 0, SALT_LENGTH)
            System.arraycopy(iv, 0, packed, SALT_LENGTH, IV_LENGTH)
            System.arraycopy(cipherText, 0, packed, SALT_LENGTH + IV_LENGTH, cipherText.size)

            return Base64Compat.encodeToString(packed, 2) // 2 = NO_WRAP
        } catch (e: Exception) {
            e.printStackTrace()
            return plainText
        }
    }

    /**
     * Decrypts AES-256-GCM cipher text generated by the encrypt function above.
     */
    fun decrypt(encryptedBase64: String, passphrase: String): String {
        if (passphrase.isEmpty() || encryptedBase64.startsWith("ENC_VOICE_") || !isBase64(encryptedBase64)) {
            // Check if it's a simulated voice assistant item
            if (encryptedBase64.startsWith("ENC_")) {
                return try {
                    val rawBase64 = encryptedBase64.removePrefix("ENC_")
                    String(Base64Compat.decode(rawBase64, 0), Charsets.UTF_8) // 0 = DEFAULT
                } catch (e: Exception) {
                    encryptedBase64
                }
            }
            return encryptedBase64
        }

        try {
            val packed = Base64Compat.decode(encryptedBase64, 2) // 2 = NO_WRAP
            if (packed.size < SALT_LENGTH + IV_LENGTH) return encryptedBase64

            // Extract bytes
            val salt = ByteArray(SALT_LENGTH)
            val iv = ByteArray(IV_LENGTH)
            val cipherTextSize = packed.size - SALT_LENGTH - IV_LENGTH
            val cipherText = ByteArray(cipherTextSize)

            System.arraycopy(packed, 0, salt, 0, SALT_LENGTH)
            System.arraycopy(packed, SALT_LENGTH, iv, 0, IV_LENGTH)
            System.arraycopy(packed, SALT_LENGTH + IV_LENGTH, cipherText, 0, cipherTextSize)

            // Derive key using extracted salt
            val keySpec = deriveKey(passphrase, salt)

            // Configure cipher
            val cipher = Cipher.getInstance("AES/GCM/NoPadding")
            val gcmSpec = GCMParameterSpec(TAG_LENGTH_BIT, iv)
            cipher.init(Cipher.DECRYPT_MODE, keySpec, gcmSpec)

            // Decrypt
            val decryptedBytes = cipher.doFinal(cipherText)
            return String(decryptedBytes, Charsets.UTF_8)
        } catch (e: Exception) {
            // Fallback for unencrypted lists or key mismatches
            return "Decryption Error (Key Mismatch)"
        }
    }

    private fun isBase64(str: String): Boolean {
        return try {
            Base64Compat.decode(str, 2)
            str.replace("\n", "").replace("\r", "").trim().length % 4 == 0
        } catch (e: Exception) {
            false
        }
    }
}

/**
 * Compatibility helper for Base64 coding that runs on both JVM unit tests and Android (any API level).
 */
object Base64Compat {
    fun encodeToString(bytes: ByteArray, flags: Int): String {
        return try {
            // Try standard Java Base64 (works on JVM and Android API >= 26)
            java.util.Base64.getEncoder().encodeToString(bytes)
        } catch (e: Throwable) {
            // Fallback to Android's Base64 class via reflection
            val clazz = Class.forName("android.util.Base64")
            val method = clazz.getMethod("encodeToString", ByteArray::class.java, Int::class.javaPrimitiveType)
            method.invoke(null, bytes, flags) as String
        }
    }

    fun decode(str: String, flags: Int): ByteArray {
        return try {
            // Try standard Java Base64
            val sanitized = str.replace("\n", "").replace("\r", "").trim()
            java.util.Base64.getDecoder().decode(sanitized)
        } catch (e: Throwable) {
            // Fallback to Android's Base64 class via reflection
            val clazz = Class.forName("android.util.Base64")
            val method = clazz.getMethod("decode", String::class.java, Int::class.javaPrimitiveType)
            method.invoke(null, str, flags) as ByteArray
        }
    }
}
